apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: author-contract
  name: author-contract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-contract
  strategy: {}
  template:
    metadata:
      labels:
        app: author-contract
    spec:
      containers:
        - image: IMAGE:TAG
          name: author-contract
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: author-contract-config
          readinessProbe:
            httpGet:
              port: 8080
              path: /author-contract/q/health/ready
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "250m"
status: {}
